### ISSUE TITLE
feature-request: Auto post Images

### ISSUE THREAD

**Issue by KingBier** [instagrambot/gramup-dm#1]
Hello,

i would like to know if its possible to auto post images from a foreign source?
What I imagine is that you can put image links with hash tags and description in the dashboard to be uploaded to Instagram automatically one after the other.
- either upload links as textfile with hashtags etc or make input fields
- post with timed delay

thanks in advance

**Comment by EKKARINza** [comment]
> Hello,
> 
> i would like to know if its possible to auto post images from a foreign source?
> What I imagine is that you can put image links with hash tags and description in the dashboard to be uploaded to Instagram automatically one after the other.
> 
> * either upload links as textfile with hashtags etc or make input fields
> * post with timed delay
> 
> thanks in advance
